//This file contains all necessary constants for the game.

#ifndef CONSTANTSINCL

//All header files used.
#include<iostream.h>
#include<string.h>
#include<fstream.h>
#include<iomanip.h>
#include<conio.h>
#include<constrea.h>
#include<stdlib.h>

const int SIZE = 4;
const int LEFT = 75;
const int RIGHT = 77;
const int UP = 72;
const int DOWN = 80;
const int keyN = 'N';
const int keyn = 'n';
const int keyP = 'P';
const int keyp = 'p';
const int keyL = 'L';
const int keyl = 'l';
const int keyX = 'X';
const int keyx = 'x';
const int keyW = 'W';
const int keyw = 'w';
const int keyA = 'A';
const int keya = 'a';
const int keyS = 'S';
const int keys = 's';
const int keyD = 'D';
const int keyd = 'd';
const int LIGHT_AQUA = 11;
const int LIGHT_GREEN = 10;
const int LIGHT_RED = 12;
#define TRUE 1
#define FALSE 0
const int EMPTY = -1;
#define CONSTANTSINCL
#endif
