//This file contains all necessary constants for the game.
#ifndef CONSTANTSINCL

const int SIZE = 3;
const int LEFT = 75;
const int RIGHT = 77;
const int UP = 72;
const int DOWN = 80;
const int keyN='N';
const int keyn='n';
const int keyP='P';
const int keyp='p';
const int keyL='L';
const int keyl='l';
const int keyX='X';
const int keyx='x';
const int keyW='W';
const int keyw='w';
const int keyA='A';
const int keya='a';
const int keyS='S';
const int keys='s';
const int keyD='D';
const int keyd='d';
const char *SAVEPATH="SAVEDATA.DAT";
#define TRUE 1
#define FALSE 0
const int EMPTY= -1;
const int PIXEL=100;
#define CONSTANTSINCL
#endif